/*
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
*/

module MessengerTopic {
#pragma DCPS_DATA_TYPE "MessengerTopic::Message"
#pragma DCPS_DATA_KEY "MessengerTopic::Message" subject_id
  @topic
  struct Message {
    string from;
    string subject;
    long subject_id;
    string text;
    long count;
  };
};

